# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='questionaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(max_length=50)),
                ('resultA', models.TextField()),
                ('resultB', models.TextField()),
                ('resultC', models.TextField()),
                ('questionA', models.TextField()),
                ('optionA1', models.CharField(max_length=50)),
                ('option_pointA1', models.IntegerField()),
                ('optionA2', models.CharField(max_length=50)),
                ('option_pointA2', models.IntegerField()),
                ('optionA3', models.CharField(max_length=50)),
                ('option_pointA3', models.IntegerField()),
                ('questionB', models.TextField()),
                ('optionB1', models.CharField(max_length=50)),
                ('option_pointB1', models.IntegerField()),
                ('optionB2', models.CharField(max_length=50)),
                ('option_pointB2', models.IntegerField()),
                ('optionB3', models.CharField(max_length=50)),
                ('option_pointB3', models.IntegerField()),
                ('questionC', models.TextField()),
                ('optionC1', models.CharField(max_length=50)),
                ('option_pointC1', models.IntegerField()),
                ('optionC2', models.CharField(max_length=50)),
                ('option_pointC2', models.IntegerField()),
                ('optionC3', models.CharField(max_length=50)),
                ('option_pointC3', models.IntegerField()),
                ('questionD', models.TextField()),
                ('optionD1', models.CharField(max_length=50)),
                ('option_pointD1', models.IntegerField()),
                ('optionD2', models.CharField(max_length=50)),
                ('option_pointD2', models.IntegerField()),
                ('optionD3', models.CharField(max_length=50)),
                ('option_pointD3', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
