# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0003_auto_20180131_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionary',
            name='resultA',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='resultB',
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='resultC',
        ),
    ]
