# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0006_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionary',
            name='respuesta_A',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='questionary',
            name='respuesta_B',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='questionary',
            name='respuesta_C',
            field=models.TextField(default=''),
        ),
    ]
