# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0007_auto_20180202_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionary',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
